const adjs = [
  "inconclusive",
  "alert",
  "bad",
  "sassy",
  "humdrum",
  "lean",
  "empty",
  "spotty",
  "lopsided",
  "full",
  "quick",
  "rambunctious",
  "disastrous",
  "cute",
  "enthusiastic",
  "animated",
  "abrupt",
  "wacky",
  "brash",
  "rich",
  "fierce",
  "cooing",
  "ludicrous",
  "selective",
  "icky",
  "recondite",
  "sable",
  "nondescript",
  "jazzy",
  "observant",
  "youthful",
  "deserted",
  "vacuous",
  "innate",
  "flippant",
  "shaky",
  "cruel",
  "light",
  "abnormal",
  "wasteful",
  "purring",
  "well-to-do",
  "endurable",
]

const anims = [
  "koala",
  "ram",
  "bison",
  "rooster",
  "capybara",
  "octopus",
  "bear",
  "mouse",
  "ape",
  "shrew",
  "hare",
  "bunny",
  "camel",
  "donkey",
  "snake",
  "lizard",
  "jaguar",
  "eagle",
  "puppy",
  "cougar",
  "tiger",
  "ox",
  "badger",
  "chamois",
  "donkey",
  "parrot",
  "walrus",
  "marmoset",
  "cheetah",
  "zebra",
  "baboon",
  "ocelot",
  "beaver",
]

export default function generator() {
  let adj = adjs[Math.floor(Math.random() * adjs.length)]
  adj = `${adj[0].toUpperCase()}${adj.slice(1)}`
  let anim = anims[Math.floor(Math.random() * anims.length)]
  anim = `${anim[0].toUpperCase()}${anim.slice(1)}`
  return [adj, anim].join(" ")
}

console.log(generator())
